language: perl

install:
  - cpanm -n File::Which File::Copy::Recursive File::Fetch Archive::Extract Module::Build File::Path Digest::SHA
  - cpanm -n --installdeps .

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - env PERL_MM_USE_DEFAULT=1 perl Build.PL
  - ./Build
  - ./Build test verbose=1

sudo: false
