language: perl

install:
  - cpanm -n --installdeps .

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - perl Build.PL
  - ./Build
  - ./Build test verbose=1

sudo: false
